import crypto from 'node:crypto';

/**
 * Where an uploaded document is stored, with no name in the path.
 *
 * Every upload site used to build its own path from the file the recruiter dropped, so a CV
 * called "Bertescu_Dumitrel_CV_Final_Readable.pdf" put the candidate's name into object storage
 * and into documents.storage_path. That is internal and never served to a client — but a name
 * in a path is a name, it turns up in logs, backups, signed URLs and bucket listings, and none
 * of those are places anyone thinks to look for one.
 *
 * The path carries the candidate id where there is one, and THE DOCUMENT'S OWN ID as the file name.
 * Nothing else. It is unique per document by construction, so no two rows can ever address the same
 * object — which is the whole point, and was not true until 2026-09-23.
 *
 * WHAT IT USED TO BE, AND WHY THAT DESTROYED FILES. The leaf was `digest(original file name)`, on
 * the reasoning that a stable key means "re-uploading the same file lands on the same key and a
 * duplicate does not silently become a second object". The premise is wrong: a digest of the NAME
 * identifies the name, not the file. Two DIFFERENT files called `CV.pdf`, both arriving before
 * either is attached, resolved to one identical key — and the upload uses `upsert: true`, so the
 * second silently overwrote the first and both rows pointed at one object ever after. It is not
 * limited to unattached documents either: the same two files dropped on the SAME candidate under
 * the same type collide in exactly the same way.
 *
 * It has already happened. `17e7988c` and `add887a9` (both "Bertescu Dumitrel", uploaded one minute
 * apart on 2026-09-16) share `cv/unattached/0592625a70b5.pdf`, and `f87ca998` shares its fate — all
 * three objects are gone from storage while their rows survive. Those rows are kept deliberately as
 * the evidence this happened (owner's decision, 2026-09-23) and are the only documents left without
 * a content hash.
 *
 * WHY THE DOCUMENT ID AND NOT THE CONTENT HASH, which 0044 already stores. A content-keyed path
 * narrows the failure rather than closing it: identical files would still share one object, and
 * identical files are real here — the same PEPLIŃSKI certificate is on file as four rows, two of
 * which already shared a path. Deleting one row's file would still take another row's with it. The
 * document id cannot collide by construction. Dedupe belongs in `content_sha256`, where it ASKS a
 * recruiter (document-hash.ts) instead of silently merging two people's storage.
 *
 * The id is generated by the caller and used for BOTH the path and the row, so nothing has to be
 * inserted before the upload — `documents.id` is a uuid the caller may supply. Verification
 * screenshots have keyed on the document id all along; this brings the file itself into line.
 *
 * One helper, used by all three upload sites, because this is exactly the kind of rule that
 * drifts when each caller spells it out for itself.
 */

/** The extension, from the file name, lower-cased and bounded. Never the name itself. */
function extensionOf(filename: string, contentType?: string | null): string {
  const fromName = filename.match(/\.([A-Za-z0-9]{1,8})$/)?.[1]?.toLowerCase();
  if (fromName) return fromName;
  const byType: Record<string, string> = {
    'application/pdf': 'pdf',
    'image/jpeg': 'jpg',
    'image/png': 'png',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'docx',
    'text/plain': 'txt',
  };
  return byType[String(contentType ?? '').toLowerCase()] ?? 'bin';
}

/** A fresh id for a document, to be used as BOTH its row id and its file name. */
export const newDocumentId = () => crypto.randomUUID();

export function documentPath(input: {
  workspaceId: string;
  /** 'cv', 'certificate', 'passport' … the document's own type, which identifies nobody. */
  type: string;
  /** The document's own id. It is what makes the path unique, so it is required. */
  documentId: string;
  /** Only to read the extension off. The name itself never reaches the path. */
  filename: string;
  contentType?: string | null;
  /** Present once the document belongs to someone; absent while it is still unattached. */
  candidateId?: string | null;
}): string {
  const ext = extensionOf(input.filename, input.contentType);
  const who = input.candidateId ?? 'unattached';
  // Refused rather than defaulted: a path built without an id would be a path that can collide, and
  // the caller silently getting one back is how this defect existed in the first place.
  const id = String(input.documentId ?? '').trim();
  if (!id) throw new Error('documentPath needs the document id — a path without one can collide and overwrite another file');
  return `${input.workspaceId}/${input.type}/${who}/${id}.${ext}`;
}

/**
 * Does a stored path still carry something that could be a name? Used by the audit.
 *
 * Both shapes pass: a uuid (what this helper now produces) and the twelve-hex digest it produced
 * before 2026-09-23. The old shape is still on 15 stored objects until the migration moves them,
 * and neither shape contains a name — the audit asks about NAMES, not about collisions.
 */
export function pathLooksNamed(path: string): boolean {
  const leaf = path.split('/').pop() ?? '';
  const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.[a-z0-9]{1,8}$/;
  const legacyDigest = /^[0-9a-f]{12}\.[a-z0-9]{1,8}$/;
  return !(uuid.test(leaf) || legacyDigest.test(leaf));
}
