/**
 * Item 24 follow-up 3, step 2 on screen: a document that names someone else is never attached without asking. Re-runs the
 * owner's report exactly — Paul Daniel Pascale's FROSIO certificate dropped on Bertescu Dumitrel's page — as a signed-in
 * recruiter in a throwaway test workspace, at 1500px and at 390px on a touch screen.
 *
 *   npx tsx --env-file=.env.local scripts/cert-mismatch-probe.tsx https://leadscout-rfbt.vercel.app
 *
 * The certificates are specimens rendered here, marked TEST SPECIMEN with made-up numbers — never the real document.
 *   1. 1500px: the Pascale certificate dropped on Bertescu Dumitrel's page asks "This certificate is for Paul Daniel
 *      Pascale — this candidate is Bertescu Dumitrel. Attach anyway, or open a record for Paul Daniel Pascale instead?";
 *      nothing is attached, and after a reload their Certificates still read 0.
 *   2. Verify's unattached documents: "Attach to someone else…" → Bertescu Dumitrel asks the same and attaches nothing;
 *      the attach route itself answers 409, with both names, to a call that does not say attach anyway.
 *   3. "Open a record for Paul Daniel Pascale" on that card opens his record, and the certificate goes on it.
 *   4. Dropped on Bertescu Dumitrel's page again, "Attach anyway" attaches it, and the trail says the names differed.
 *   5. A certificate printed "BERTESCU, Dumitrel" — the same name in another order and case — attaches with no question.
 *   6. 390px, touch: the Pascale certificate through the page's file picker asks the same, attaches nothing, and the
 *      question fits the screen.
 *   7. Every read was metered as test traffic.
 * Everything it made is removed afterwards; a leftover fails the run.
 */
import React from 'react';
import fs from 'node:fs';
import { createClient } from '@supabase/supabase-js';
import { chromium, type Page } from 'playwright';
import { Document, Page as PdfPage, Text, View, renderToBuffer } from '@react-pdf/renderer';
import { followAllForProbe, markWorkspaceTest, removeProbe } from '../src/lib/test-data';
import { hasCandidateCrm } from '../src/lib/schema-features';

const BASE = process.argv[2] ?? 'http://localhost:3100';
const EMAIL = `cert-mismatch-probe+${Date.now()}@rfbt-recruitment.com`;
const PASSWORD = `probe-${Date.now()}-0123456789`;
const PASCALE = '.cache/probe-frosio-pascale.pdf';
const BERTESCU = '.cache/probe-frosio-bertescu.pdf';
const admin = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } });
const shim = 'globalThis.__name = globalThis.__name || function (f) { return f; };';

let failures = 0;
const check = (ok: boolean, what: string, detail = '') => { if (!ok) failures++; console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${what}${detail ? ` — ${detail}` : ''}`); };
const flat = (s: string) => s.replace(/\s+/g, ' ').trim();
const sideways = (p: Page) => p.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
const hydrated = (p: Page) => p.waitForFunction(() => document.documentElement.dataset.hydrated === 'true', undefined, { timeout: 60000 }).catch(() => {});
const ASKED = /this certificate is for paul daniel pascale — this candidate is bertescu dumitrel\. attach anyway, or open a record for paul daniel pascale instead\?/i;

/** A FROSIO-shaped specimen for the extraction to read a holder from: clearly marked, with a made-up number. */
async function specimen(file: string, holder: string, number: string) {
  const rows = [['Holder', holder], ['Certificate number', number], ['Level', 'Inspector Level III'], ['Date of issue', '18 January 2023'], ['Valid until', '17 January 2028']];
  const doc = (
    <Document>
      <PdfPage size="A4" style={{ padding: 44, fontSize: 10, fontFamily: 'Helvetica', lineHeight: 1.5 }}>
        <View style={{ backgroundColor: '#F3F5F7', padding: 8, marginBottom: 14, fontSize: 9 }}>
          <Text>TEST SPECIMEN — generated by LeadScout&apos;s cert-mismatch probe. This is not a real certificate and the number below is not a real FROSIO number.</Text>
        </View>
        <Text style={{ fontSize: 18, fontFamily: 'Helvetica-Bold', marginBottom: 2 }}>FROSIO Certificate — Surface Treatment Inspector</Text>
        <Text style={{ color: '#555' }}>FROSIO, the Norwegian Professional Council for Education and Certification of Inspectors for Surface Treatment</Text>
        <View style={{ marginTop: 18 }}>
          {rows.map(([k, v]) => (
            <View key={k} style={{ flexDirection: 'row', marginBottom: 2 }}><Text style={{ width: 130, color: '#555' }}>{k}</Text><Text>{v}</Text></View>
          ))}
        </View>
      </PdfPage>
    </Document>
  );
  fs.writeFileSync(file, await renderToBuffer(doc));
}

/** A real drag from outside the browser onto `target`: a DataTransfer carrying the PDF, dispatched as dragover and drop. */
async function dropFile(page: Page, target: string, file: string) {
  const b64 = fs.readFileSync(file).toString('base64');
  const name = file.split('/').pop()!;
  const dt = await page.evaluateHandle(({ b64, name }) => {
    const bytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
    const t = new DataTransfer();
    t.items.add(new File([bytes], name, { type: 'application/pdf' }));
    return t;
  }, { b64, name });
  await page.dispatchEvent(target, 'dragover', { dataTransfer: dt });
  await page.dispatchEvent(target, 'drop', { dataTransfer: dt });
}

// Called on a freshly loaded page, where no result is on screen until intake has answered.
const docSettled = (p: Page) => p.waitForFunction(() => document.querySelector('[data-candidate-doc-drop]')?.getAttribute('data-candidate-doc-busy') === 'false'
  && !!document.querySelector('[data-candidate-doc-result]'), undefined, { timeout: 180000 }).then(() => true).catch(() => false);

(async () => {
  fs.mkdirSync('.cache', { recursive: true });
  await specimen(PASCALE, 'Paul Daniel Pascale', 'SPECIMEN-0001');
  await specimen(BERTESCU, 'BERTESCU, Dumitrel', 'SPECIMEN-0002');

  const crm = await hasCandidateCrm(admin);
  const { data: created, error } = await admin.auth.admin.createUser({ email: EMAIL, password: PASSWORD, email_confirm: true, user_metadata: { name: 'Cert Mismatch Probe', agency: 'Cert Mismatch Probe' } });
  if (error) { console.error('could not create the probe user:', error.message); process.exit(1); }
  const uid = created.user!.id;
  const { data: me } = await admin.from('users').select('workspace_id').eq('id', uid).maybeSingle();
  const workspace = me?.workspace_id as string;
  await markWorkspaceTest(admin, workspace);
  await admin.from('users').update({ role: 'recruiter', onboarding_day: 30 }).eq('id', uid);
  await followAllForProbe(admin, uid);
  const startedAt = new Date().toISOString();

  const ref = `PROBE${Date.now().toString().slice(-5).replace(/\d/g, (d) => 'ABCDEFGHIJ'[Number(d)])}-F-9109`;
  const { data: cand, error: cErr } = await admin.from('candidates').insert({
    workspace_id: workspace, reference_code: ref, trade_code: 'F', full_name: 'Bertescu Dumitrel', trade: 'Surface treatment inspector',
    profile: { full_name: 'Bertescu Dumitrel', trade: 'Surface treatment inspector', trade_code: 'F', pii: {} }, created_via: 'manual', created_by: uid, is_test: true,
    ...(crm ? { owner_id: uid } : {}),
  }).select('id').single();
  if (cErr || !cand) { console.error('seeding failed:', cErr?.message); await removeProbe(admin, uid, workspace, null, { clearContent: true }); process.exit(1); }

  const docs = async () => ((await admin.from('documents').select('id, candidate_id, attach_reason, holder:extracted->>holder').eq('workspace_id', workspace).eq('type', 'certificate')).data ?? []) as any[];
  const pageUrl = `${BASE}/app/candidates/${cand.id}`;

  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({ viewport: { width: 1500, height: 1000 } });
    await page.addInitScript({ content: shim });
    await page.goto(`${BASE}/login`, { waitUntil: 'domcontentloaded', timeout: 60000 });
    await page.fill('input[type=email]', EMAIL);
    await page.fill('input[type=password]', PASSWORD);
    await page.click('form button:not([type=button])');
    await page.waitForURL(/\/app\//, { timeout: 60000 }).catch(() => {});
    const openPage = async (p: Page) => { await p.goto(pageUrl, { waitUntil: 'domcontentloaded', timeout: 60000 }); await hydrated(p); };

    // ---- 1. The owner's report, re-run
    await openPage(page);
    await dropFile(page, '[data-candidate-doc-drop]', PASCALE);
    const settled = await docSettled(page);
    const asked = flat(await page.locator('[data-mismatch-question]').first().innerText().catch(() => ''));
    let all = await docs();
    check(settled && ASKED.test(asked), "1500px: Paul Daniel Pascale's certificate dropped on Bertescu Dumitrel's page asks, in the owner's words", asked.slice(0, 220));
    check(all.length === 1 && all[0].candidate_id === null, '1500px: nothing is attached — the certificate is stored, attached to nobody', JSON.stringify(all.map((d) => ({ holder: d.holder, attached: !!d.candidate_id }))));
    await openPage(page);
    const heading = flat(await page.locator('[data-candidate-section="certificates"] h2').innerText().catch(() => ''));
    check((await page.locator('[data-candidate-certificate]').count()) === 0 && /Certificates · 0/.test(heading), "1500px: after a reload Bertescu Dumitrel's Certificates still read 0", heading);
    const pascaleDoc = all[0]?.id as string;

    // ---- 2. Verify's unattached card, and the route itself
    await page.goto(`${BASE}/app/verify`, { waitUntil: 'domcontentloaded', timeout: 60000 });
    await hydrated(page);
    await page.getByRole('button', { name: /attached to nobody/ }).click();
    const card = page.locator(`[data-unattached-doc="${pascaleDoc}"]`);
    await card.getByRole('button', { name: 'Attach to someone else…' }).click();
    await card.locator('select').selectOption(cand.id);
    await card.getByRole('button', { name: 'Attach', exact: true }).click();
    await card.locator('[data-mismatch-question]').waitFor({ timeout: 30000 }).catch(() => {});
    const askedOnVerify = flat(await card.locator('[data-mismatch-question]').innerText().catch(() => ''));
    all = await docs();
    check(ASKED.test(askedOnVerify) && all.every((d) => d.candidate_id === null), "Verify's unattached card: choosing Bertescu Dumitrel by hand asks the same, and attaches nothing", askedOnVerify.slice(0, 200));
    const direct = await page.request.post(`${BASE}/api/verify/attach`, { data: { documentId: pascaleDoc, candidateId: cand.id } });
    const dj = await direct.json().catch(() => ({}));
    all = await docs();
    check(direct.status() === 409 && /pascale/i.test(String(dj?.mismatch?.holder)) && /bertescu/i.test(String(dj?.mismatch?.candidate?.name)) && all.every((d) => d.candidate_id === null),
      'the attach route refuses it — 409 with both names — unless the call says attach anyway', `HTTP ${direct.status()} · ${String(dj?.error ?? '').slice(0, 120)}`);

    // ---- 3. Open a record for the person named
    await card.locator('[data-mismatch-open]').click();
    await page.getByText('Settled this session').waitFor({ timeout: 30000 }).catch(() => {});
    const { data: pascale } = await admin.from('candidates').select('id, full_name').eq('workspace_id', workspace).ilike('full_name', '%pascale%');
    all = await docs();
    const onPascale = all.find((d) => d.id === pascaleDoc)?.candidate_id;
    check((pascale ?? []).length === 1 && onPascale === pascale![0].id, '"Open a record for Paul Daniel Pascale" opens his record, and the certificate goes on him, not on Bertescu Dumitrel', `${(pascale ?? []).length} record(s) · on him: ${onPascale === pascale?.[0]?.id}`);

    // ---- 4. Attach anyway — the genuine edge case
    await openPage(page);
    await dropFile(page, '[data-candidate-doc-drop]', PASCALE);
    await docSettled(page);
    await page.locator('[data-mismatch-attach]').first().click();
    await page.waitForSelector('[data-mismatch-done="attached"]', { timeout: 30000 }).catch(() => {});
    all = await docs();
    const anyway = all.filter((d) => d.candidate_id === cand.id);
    check(anyway.length === 1 && /attached anyway by .+ after being told the names differ \(paul daniel pascale → bertescu dumitrel\)/i.test(String(anyway[0].attach_reason)),
      '"Attach anyway" attaches it to Bertescu Dumitrel, and the trail says the names differed', String(anyway[0]?.attach_reason ?? 'not attached').slice(0, 200));

    // ---- 5. Their own name, in another order and case
    await openPage(page);
    await dropFile(page, '[data-candidate-doc-drop]', BERTESCU);
    const ownSettled = await docSettled(page);
    const ownQuestion = await page.locator('[data-mismatch-question]').count();
    all = await docs();
    const own = all.filter((d) => d.candidate_id === cand.id && /bertescu/i.test(String(d.holder)));
    check(ownSettled && ownQuestion === 0 && own.length === 1, 'a certificate printed "BERTESCU, Dumitrel" — their name in another order and case — attaches to them with no question', `question ${ownQuestion} · attached ${own.length}`);

    // ---- 6. 390px, touch, through the file picker
    const phone = await browser.newContext({ storageState: await page.context().storageState(), viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true });
    const m = await phone.newPage();
    await m.addInitScript({ content: shim });
    await openPage(m);
    const before = (await docs()).filter((d) => d.candidate_id === cand.id).length;
    const chooser = await Promise.all([m.waitForEvent('filechooser', { timeout: 30000 }), m.locator('[data-candidate-doc-drop]').tap()]).then(([c]) => c).catch(() => null);
    if (chooser) await chooser.setFiles(PASCALE);
    const phoneSettled = !!chooser && await docSettled(m);
    const phoneAsked = flat(await m.locator('[data-mismatch-question]').first().innerText().catch(() => ''));
    const after = (await docs()).filter((d) => d.candidate_id === cand.id).length;
    check(phoneSettled && ASKED.test(phoneAsked) && after === before, '390px: the Pascale certificate through the file picker asks the same, and attaches nothing', phoneAsked.slice(0, 160));
    const box = await m.locator('[data-mismatch-question]').first().boundingBox();
    check(await sideways(m) <= 1 && !!box && box.x >= 0 && box.x + box.width <= 391, '390px: the question fits the screen, nothing scrolls sideways', `${await sideways(m)}px · question ${box ? `${Math.round(box.x)}–${Math.round(box.x + box.width)}px` : 'not found'}`);
    await phone.close();

    // ---- 7. metered
    const { data: cost } = await admin.from('cost_log').select('kind, eur, detail').eq('workspace_id', workspace).gte('created_at', startedAt);
    check((cost ?? []).length > 0 && (cost ?? []).every((c: any) => String(c.detail).startsWith('test workspace')), 'every read was metered as test traffic', `${(cost ?? []).length} attempt(s) · €${(cost ?? []).reduce((a: number, c: any) => a + Number(c.eur), 0).toFixed(4)}`);
  } finally {
    await browser.close();
    for (const f of [PASCALE, BERTESCU]) fs.rmSync(f, { force: true });
    const leftBehind = await removeProbe(admin, uid, workspace, null, { clearContent: true });
    if (leftBehind) { failures++; console.log(`\n  FAIL  cleanup — ${leftBehind}`); } else console.log('\nprobe user, its workspace and everything it made removed');
  }
  console.log(failures === 0 ? 'cert mismatch probe: all checks passed' : `cert mismatch probe: ${failures} check(s) failed`);
  process.exitCode = failures === 0 ? 0 : 1;
})();
