/**
 * Test PDFs for exercising Verify end to end: one CV, one certificate.
 *   npx tsx scripts/make-fixtures.tsx
 *
 * The CV deliberately carries a name, phone, email and named employers so both PII gates have
 * something real to catch. The certificate is clearly marked as a specimen and its number is
 * not a real PCN number — it exists to drive the extraction and the register lookup, and the
 * honest expected result from BINDT is "not found".
 */
import React from 'react';
import fs from 'fs';
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer';

const s = StyleSheet.create({
  page: { padding: 44, fontSize: 10, fontFamily: 'Helvetica', lineHeight: 1.5 },
  h1: { fontSize: 18, fontFamily: 'Helvetica-Bold', marginBottom: 2 },
  h2: { fontSize: 11, fontFamily: 'Helvetica-Bold', marginTop: 14, marginBottom: 4 },
  muted: { color: '#555' },
  row: { flexDirection: 'row', marginBottom: 2 },
  label: { width: 130, color: '#555' },
  banner: { backgroundColor: '#F3F5F7', padding: 8, marginBottom: 14, fontSize: 9 },
});

const Cv = () => (
  <Document>
    <Page size="A4" style={s.page}>
      <Text style={s.h1}>Marko Jovanović</Text>
      <Text style={s.muted}>Industrial painter / blaster · Beograd, Serbia</Text>
      <Text style={s.muted}>+381 64 123 4567 · marko.jovanovic@example.com · Bulevar Kralja 12, 11000 Beograd</Text>
      <Text style={s.muted}>Date of birth: 14 June 1988 · Serbian passport · EU work permit</Text>

      <Text style={s.h2}>Certificates</Text>
      <Text>FROSIO Inspector Level II, certificate 12 8471, issued 15 March 2023, valid to 14 March 2028</Text>
      <Text>Offshore medical certificate, valid to 4 September 2027</Text>
      <Text>GWO Basic Safety Training, valid to 11 November 2026</Text>

      <Text style={s.h2}>Experience</Text>
      <Text>2025–26 · Dragados Offshore, Cádiz — offshore substation painting and blasting, 8:2 rotation.</Text>
      <Text>Airless spray application, grit blasting to Sa 2.5, DFT and WFT control, dew-point discipline.</Text>
      <Text>2024 · Bladt Industries, Aalborg — monopile coating for offshore wind, 2:2 rotation.</Text>
      <Text>2022–23 · Goša FOM, Smederevo — industrial steel structures, surface treatment and painting.</Text>

      <Text style={s.h2}>Skills and languages</Text>
      <Text>Airless spray, grit blasting, confined space, working at height, coating inspection support.</Text>
      <Text>Serbian (native), English (working), Spanish (basic).</Text>

      <Text style={s.h2}>Availability</Text>
      <Text>Available from 4 October 2026. Prefers 2:2 or 8:2 rotations. Holds own PPE.</Text>
    </Page>
  </Document>
);

const Cert = () => (
  <Document>
    <Page size="A4" style={s.page}>
      <View style={s.banner}>
        <Text>TEST SPECIMEN — generated by LeadScout to exercise the Verify pipeline. This is not a real certificate and the number below is not a real PCN number.</Text>
      </View>
      <Text style={s.h1}>PCN Certificate of Competence</Text>
      <Text style={s.muted}>British Institute of Non-Destructive Testing</Text>

      <View style={{ marginTop: 18 }}>
        {[
          ['Certificate number', 'PCN-TEST-000000'],
          ['PCN number', '999999'],
          ['Holder', 'Dragan Veselinović'],
          ['Method', 'Ultrasonic Testing'],
          ['Level', '2'],
          ['Sector', 'Weldments'],
          ['Scope', 'Welds, plate, pipe'],
          ['Date of issue', '12 November 2022'],
          ['Expiry date', '11 November 2027'],
        ].map(([k, v]) => (
          <View style={s.row} key={k}>
            <Text style={s.label}>{k}</Text>
            <Text>{v}</Text>
          </View>
        ))}
      </View>

      <Text style={{ marginTop: 24, fontSize: 9, color: '#555' }}>
        Verify at www.bindt.org/Certification/pcn-certificate-verification/
      </Text>
    </Page>
  </Document>
);

(async () => {
  fs.mkdirSync('fixtures', { recursive: true });
  fs.writeFileSync('fixtures/test-cv.pdf', await renderToBuffer(<Cv />));
  fs.writeFileSync('fixtures/test-certificate.pdf', await renderToBuffer(<Cert />));
  for (const f of ['fixtures/test-cv.pdf', 'fixtures/test-certificate.pdf']) {
    console.log(`${f} — ${fs.statSync(f).size} bytes`);
  }
})();
